# Generated by Django 5.1.2 on 2024-11-24 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0002_mentor_created_student_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 14, 59, 5, 843762)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 14, 59, 5, 843762)),
        ),
    ]
