# Generated by Django 5.1.2 on 2024-11-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0004_alter_mentor_created_alter_student_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNum',
            field=models.IntegerField(max_length=50),
        ),
    ]
