# Generated by Django 5.1.2 on 2024-11-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0006_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='collegeId',
            field=models.IntegerField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNum',
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
