# Generated by Django 5.1.2 on 2024-11-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0007_alter_mentor_collegeid_alter_mentor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='collegeId',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollNum',
            field=models.IntegerField(unique=True),
        ),
    ]
