# Generated by Django 5.1.2 on 2024-11-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0008_alter_mentor_collegeid_alter_student_rollnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='password',
            field=models.CharField(default='this', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='this', max_length=50),
            preserve_default=False,
        ),
    ]
