# Generated by Django 5.1.2 on 2025-08-27 11:59

import django.db.models.deletion
import django.db.models.manager
import recpaper_app.utils.blob_storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.IntegerField()),
                ('title', models.CharField(max_length=500, unique=True)),
                ('description', models.TextField()),
                ('objective', models.TextField()),
                ('status', models.CharField(max_length=500)),
                ('keyword', models.TextField()),
                ('platform', models.TextField()),
                ('github_link', models.CharField(max_length=500, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('group', models.BooleanField(default=False)),
                ('collaboration', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('is_student', models.BooleanField(default=True)),
                ('is_faculty', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('FACULTY', 'Faculty')], max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('verified_by_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(max_length=500, storage=recpaper_app.utils.blob_storage.VercelBlobStorage(), upload_to='project_files')),
                ('message', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recpaper_app.project')),
            ],
            options={
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_mentor', to='recpaper_app.user'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_author', to='recpaper_app.user'),
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_project', to='recpaper_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member', to='recpaper_app.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('project_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recpaper_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_writer', to='recpaper_app.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
            ],
            options={
                'ordering': ['username'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('recpaper_app.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('recpaper_app.user',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Project_log',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remark_by_mentor', models.TextField()),
                ('current_status', models.TextField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recpaper_app.project')),
                ('mentor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recpaper_app.faculty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
