# Generated by Django 5.1.2 on 2025-04-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='keyword',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.AddField(
            model_name='project',
            name='keyword',
            field=models.TextField(default='other'),
            preserve_default=False,
        ),
    ]
