# Generated by Django 5.1.2 on 2025-01-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0003_remove_comment_project_id_remove_comment_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='objective',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
