# Generated by Django 5.1.2 on 2024-11-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
