# Generated by Django 5.1.2 on 2025-01-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0004_alter_project_description_alter_project_github_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
