# Generated by Django 5.1.2 on 2025-04-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0004_mentor_alter_project_mentor_alter_project_log_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
