# Generated by Django 5.1.2 on 2025-01-06 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0005_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='abcd', max_length=100),
            preserve_default=False,
        ),
    ]
