# Generated by Django 5.1.2 on 2025-04-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0005_mentor_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='roll_no',
            field=models.CharField(default=12312, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='roll_no',
            field=models.CharField(default=12321, max_length=50),
            preserve_default=False,
        ),
    ]
