# Generated by Django 5.1.2 on 2025-01-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0006_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_feculty',
            new_name='is_faculty',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project_log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project_log',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
