# Generated by Django 5.1.2 on 2025-04-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0006_mentor_roll_no_user_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roll_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
