# Generated by Django 5.1.2 on 2025-01-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0007_rename_is_feculty_user_is_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_log',
            name='user_uuid',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_uuid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='project_log',
            name='current_status',
            field=models.TextField(null=True),
        ),
    ]
