# Generated by Django 5.1.2 on 2025-04-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0007_alter_user_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='platform',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
        migrations.AddField(
            model_name='project',
            name='platform',
            field=models.TextField(default='Python, vs code'),
            preserve_default=False,
        ),
    ]
