# Generated by Django 5.1.2 on 2025-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0009_alter_project_log_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='keyword',
            field=models.CharField(default='python', max_length=500),
            preserve_default=False,
        ),
    ]
