# Generated by Django 5.1.2 on 2025-05-07 15:31

import django.db.models.deletion
import recpaper_app.utils.blob_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0010_files'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name_plural': 'Files'},
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(storage=recpaper_app.utils.blob_storage.VercelBlobStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='files',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recpaper_app.project'),
        ),
    ]
