# Generated by Django 5.1.2 on 2025-05-07 16:35

import recpaper_app.utils.blob_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0011_alter_files_options_alter_files_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(max_length=500, storage=recpaper_app.utils.blob_storage.VercelBlobStorage(), upload_to='project_files'),
        ),
    ]
