# Generated by Django 5.1.2 on 2025-05-17 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0012_alter_files_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roll_no',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='project',
            name='group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('TEACHER', 'Teacher')], default='STUDENT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='verified_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_project', to='recpaper_app.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member', to='recpaper_app.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
