# Generated by Django 5.1.2 on 2025-05-23 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0014_faculty_student_alter_user_role_alter_project_mentor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_mentor', to='recpaper_app.user'),
        ),
    ]
