# Generated by Django 5.1.2 on 2025-05-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0015_alter_project_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
