# Generated by Django 5.1.2 on 2025-05-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0017_project_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='files',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
