# Generated by Django 5.1.2 on 2025-06-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0018_alter_faculty_options_files_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaboration',
            field=models.BooleanField(default=False),
        ),
    ]
