# Generated by Django 5.1.2 on 2025-08-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recpaper_app', '0019_project_collaboration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
